## W0128 (redeclared-assigned-name)

### :x: Problematic code:

```python
foo = 5

foo = 6
```

### :heavy_check_mark: Correct code:

```python
foo = 5

diff_foo = 6
```

### Rationale:

Emitted when we detect that a variable name was assigned multiple
times in the same assignment.

### Related resources:

- [Issue Tracker](https://github.com/PyCQA/pylint/issues?q=is%3Aissue+%22redeclared-assigned-name%22+OR+%22W0128%22)
