## R1704 (redefined-argument-from-local)

### :x: Problematic code:

```python
i = 15
for i in range(10):
  print(i)
```

### :heavy_check_mark: Correct code:

```python
x = 15
for i in range(10):
  print(i)
```

### Rationale:

Used when a local name is redefining an argument, which might suggest a
potential error. This is taken in account only for a handful of name binding
operations, such as for iteration, with statement assignment and exception
handler assignment.

### Related resources:

- [Issue Tracker](https://github.com/PyCQA/pylint/issues?q=is%3Aissue+%22redefined-argument-from-local%22+OR+%22R1704%22)
