## E0701 (bad-except-order)

### :x: Problematic code:

```python
try:
    # if the line below raises a TypeError then it will never reach
    # the TypeError exception because it will be caught by Exception 
    print(int(input()))
except Exception:
    raise
except TypeError:
    raise
```

### :heavy_check_mark: Correct code:

```python
try:
    print(int(input()))
except TypeError:
    raise
except Exception:
    raise
```

### Rationale:

Occurs when the except clauses are not in the correct order: from more specific
to more generic. If the order is not fixed, some exceptions may not be
caught by the most specific handler.

### Related resources:

- [Issue Tracker](https://github.com/PyCQA/pylint/issues?q=is%3Aissue+%22bad-except-order%22+OR+%22E0701%22)
