## W0714 (overlapping-except)

### :x: Problematic code:

```python
try:
    pass
except (ValueError, IOError, OSError):
    # ValueError inherits from OSError
    # IOError is an alias for OSError
    pass
```

### :heavy_check_mark: Correct code:

```python
try:
    pass
except (ValueError, OSError):
    # ValueError inherits from OSError
    pass
```

### Rationale:

Occurs when exceptions in handler overlap or are identical.

### Related resources:

- [Issue Tracker](https://github.com/PyCQA/pylint/issues?q=is%3Aissue+%22overlapping-except%22+OR+%22W0714%22)
